 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/org_branches", type: :request do
  # OrgBranch. As you add validations to OrgBranch, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrgBranch.create! valid_attributes
      get org_branches_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      org_branch = OrgBranch.create! valid_attributes
      get org_branch_url(org_branch)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_org_branch_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      org_branch = OrgBranch.create! valid_attributes
      get edit_org_branch_url(org_branch)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrgBranch" do
        expect {
          post org_branches_url, params: { org_branch: valid_attributes }
        }.to change(OrgBranch, :count).by(1)
      end

      it "redirects to the created org_branch" do
        post org_branches_url, params: { org_branch: valid_attributes }
        expect(response).to redirect_to(org_branch_url(OrgBranch.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrgBranch" do
        expect {
          post org_branches_url, params: { org_branch: invalid_attributes }
        }.to change(OrgBranch, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post org_branches_url, params: { org_branch: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested org_branch" do
        org_branch = OrgBranch.create! valid_attributes
        patch org_branch_url(org_branch), params: { org_branch: new_attributes }
        org_branch.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the org_branch" do
        org_branch = OrgBranch.create! valid_attributes
        patch org_branch_url(org_branch), params: { org_branch: new_attributes }
        org_branch.reload
        expect(response).to redirect_to(org_branch_url(org_branch))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        org_branch = OrgBranch.create! valid_attributes
        patch org_branch_url(org_branch), params: { org_branch: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested org_branch" do
      org_branch = OrgBranch.create! valid_attributes
      expect {
        delete org_branch_url(org_branch)
      }.to change(OrgBranch, :count).by(-1)
    end

    it "redirects to the org_branches list" do
      org_branch = OrgBranch.create! valid_attributes
      delete org_branch_url(org_branch)
      expect(response).to redirect_to(org_branches_url)
    end
  end
end
